name       : which
version    : '2.21'
release    : 5
source     :
    - https://mirrors.rit.edu/gnu/which/which-2.21.tar.gz : f4a245b94124b377d8b49646bf421f9155d36aa7614b6ebf83705d3ffc76eaad
license    : GPL-3.0-only
component  : system.base
summary    : Find program in path
description: |
    Find a program in the path and display its location
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
