name       : which
version    : '2.21'
release    : 3
source     :
    - http://ftp.gnu.org/gnu/which/which-2.21.tar.gz : f4a245b94124b377d8b49646bf421f9155d36aa7614b6ebf83705d3ffc76eaad
license    :
    - GPL-3.0
summary    : Find program in path
component  : system.base
description: |
    Find a program in the path and display its location
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
